f2fs: fix F2FS_RW_ATTR_640 for updated F2FS_ATTR_OFFSET signature
* F2FS_ATTR_OFFSET now requires an additional _size argument. Update F2FS_RW_ATTR_640 to pass sizeof_field() similarly to F2FS_RW_ATTR.

../fs/f2fs/sysfs.c:1336:1: error: too few arguments provided to function-like macro invocation
 1336 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_gc_stat, sec_stat);
      | ^
../fs/f2fs/sysfs.c:1266:39: note: expanded from macro 'F2FS_RW_ATTR_640'
 1266 |                 offsetof(struct struct_name, elname))
      |                                                     ^
../fs/f2fs/sysfs.c:1241:9: note: macro 'F2FS_ATTR_OFFSET' defined here
 1241 | #define F2FS_ATTR_OFFSET(_struct_type, _name, _mode, _show, _store, _offset, _size)       |         ^
../fs/f2fs/sysfs.c:1336:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 1336 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_gc_stat, sec_stat);
      | ^
      | int
../fs/f2fs/sysfs.c:1264:2: note: expanded from macro 'F2FS_RW_ATTR_640'
 1264 |         F2FS_ATTR_OFFSET(struct_type, name, 0640,                     |         ^
../fs/f2fs/sysfs.c:1337:1: error: too few arguments provided to function-like macro invocation
 1337 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_io_stat, sec_stat);
      | ^
../fs/f2fs/sysfs.c:1266:39: note: expanded from macro 'F2FS_RW_ATTR_640'
 1266 |                 offsetof(struct struct_name, elname))
      |                                                     ^
../fs/f2fs/sysfs.c:1241:9: note: macro 'F2FS_ATTR_OFFSET' defined here
 1241 | #define F2FS_ATTR_OFFSET(_struct_type, _name, _mode, _show, _store, _offset, _size)       |         ^
../fs/f2fs/sysfs.c:1337:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 1337 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_io_stat, sec_stat);
      | ^
      | int
../fs/f2fs/sysfs.c:1264:2: note: expanded from macro 'F2FS_RW_ATTR_640'
 1264 |         F2FS_ATTR_OFFSET(struct_type, name, 0640,                     |         ^
../fs/f2fs/sysfs.c:1338:1: error: too few arguments provided to function-like macro invocation
 1338 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_fsck_stat, sec_fsck_stat);
      | ^
../fs/f2fs/sysfs.c:1266:39: note: expanded from macro 'F2FS_RW_ATTR_640'
 1266 |                 offsetof(struct struct_name, elname))
      |                                                     ^
../fs/f2fs/sysfs.c:1241:9: note: macro 'F2FS_ATTR_OFFSET' defined here
 1241 | #define F2FS_ATTR_OFFSET(_struct_type, _name, _mode, _show, _store, _offset, _size)       |         ^
../fs/f2fs/sysfs.c:1338:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 1338 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_fsck_stat, sec_fsck_stat);
      | ^
      | int
../fs/f2fs/sysfs.c:1264:2: note: expanded from macro 'F2FS_RW_ATTR_640'
 1264 |         F2FS_ATTR_OFFSET(struct_type, name, 0640,                     |         ^
../fs/f2fs/sysfs.c:1346:1: error: too few arguments provided to function-like macro invocation
 1346 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_defrag_stat, s_sec_part_best_extents);
      | ^
../fs/f2fs/sysfs.c:1266:39: note: expanded from macro 'F2FS_RW_ATTR_640'
 1266 |                 offsetof(struct struct_name, elname))
      |                                                     ^
../fs/f2fs/sysfs.c:1241:9: note: macro 'F2FS_ATTR_OFFSET' defined here
 1241 | #define F2FS_ATTR_OFFSET(_struct_type, _name, _mode, _show, _store, _offset, _size)       |         ^
../fs/f2fs/sysfs.c:1346:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 1346 | F2FS_RW_ATTR_640(F2FS_SBI, f2fs_sb_info, sec_defrag_stat, s_sec_part_best_extents);
      | ^
      | int
../fs/f2fs/sysfs.c:1264:2: note: expanded from macro 'F2FS_RW_ATTR_640'
 1264 |         F2FS_ATTR_OFFSET(struct_type, name, 0640,                     |         ^
../fs/f2fs/sysfs.c:1503:2: error: use of undeclared identifier 'f2fs_attr_sec_gc_stat'; did you mean 'f2fs_attr_sec_fs_stat'?
 1503 |         ATTR_LIST(sec_gc_stat),
      |         ^~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1440:27: note: expanded from macro 'ATTR_LIST'
 1440 | #define ATTR_LIST(name) (&f2fs_attr_##name.attr)
      |                           ^~~~~~~~~~~~~~~~
<scratch space>:20:1: note: expanded from here
   20 | f2fs_attr_sec_gc_stat
      | ^~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1360:1: note: 'f2fs_attr_sec_fs_stat' declared here
 1360 | F2FS_GENERAL_RO_ATTR(sec_fs_stat);
      | ^
../fs/f2fs/sysfs.c:1269:25: note: expanded from macro 'F2FS_GENERAL_RO_ATTR'
 1269 | static struct f2fs_attr f2fs_attr_##name = __ATTR(name, 0444, name##_show, NULL)
      |                         ^
<scratch space>:25:1: note: expanded from here
   25 | f2fs_attr_sec_fs_stat
      | ^
../fs/f2fs/sysfs.c:1504:2: error: use of undeclared identifier 'f2fs_attr_sec_io_stat'; did you mean 'f2fs_attr_sec_fs_stat'?
 1504 |         ATTR_LIST(sec_io_stat),
      |         ^~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1440:27: note: expanded from macro 'ATTR_LIST'
 1440 | #define ATTR_LIST(name) (&f2fs_attr_##name.attr)
      |                           ^~~~~~~~~~~~~~~~
<scratch space>:21:1: note: expanded from here
   21 | f2fs_attr_sec_io_stat
      | ^~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1360:1: note: 'f2fs_attr_sec_fs_stat' declared here
 1360 | F2FS_GENERAL_RO_ATTR(sec_fs_stat);
      | ^
../fs/f2fs/sysfs.c:1269:25: note: expanded from macro 'F2FS_GENERAL_RO_ATTR'
 1269 | static struct f2fs_attr f2fs_attr_##name = __ATTR(name, 0444, name##_show, NULL)
      |                         ^
<scratch space>:25:1: note: expanded from here
   25 | f2fs_attr_sec_fs_stat
      | ^
../fs/f2fs/sysfs.c:1505:2: error: use of undeclared identifier 'f2fs_attr_sec_fsck_stat'; did you mean 'f2fs_attr_sec_fs_stat'?
 1505 |         ATTR_LIST(sec_fsck_stat),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1440:27: note: expanded from macro 'ATTR_LIST'
 1440 | #define ATTR_LIST(name) (&f2fs_attr_##name.attr)
      |                           ^~~~~~~~~~~~~~~~
<scratch space>:22:1: note: expanded from here
   22 | f2fs_attr_sec_fsck_stat
      | ^~~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1360:1: note: 'f2fs_attr_sec_fs_stat' declared here
 1360 | F2FS_GENERAL_RO_ATTR(sec_fs_stat);
      | ^
../fs/f2fs/sysfs.c:1269:25: note: expanded from macro 'F2FS_GENERAL_RO_ATTR'
 1269 | static struct f2fs_attr f2fs_attr_##name = __ATTR(name, 0444, name##_show, NULL)
      |                         ^
<scratch space>:25:1: note: expanded from here
   25 | f2fs_attr_sec_fs_stat
      | ^
../fs/f2fs/sysfs.c:1513:2: error: use of undeclared identifier 'f2fs_attr_sec_defrag_stat'; did you mean
      'f2fs_attr_sec_fs_stat'?
 1513 |         ATTR_LIST(sec_defrag_stat),
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1440:27: note: expanded from macro 'ATTR_LIST'
 1440 | #define ATTR_LIST(name) (&f2fs_attr_##name.attr)
      |                           ^~~~~~~~~~~~~~~~
<scratch space>:30:1: note: expanded from here
   30 | f2fs_attr_sec_defrag_stat
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
../fs/f2fs/sysfs.c:1360:1: note: 'f2fs_attr_sec_fs_stat' declared here
 1360 | F2FS_GENERAL_RO_ATTR(sec_fs_stat);
      | ^
../fs/f2fs/sysfs.c:1269:25: note: expanded from macro 'F2FS_GENERAL_RO_ATTR'
 1269 | static struct f2fs_attr f2fs_attr_##name = __ATTR(name, 0444, name##_show, NULL)
      |                         ^
<scratch space>:25:1: note: expanded from here
   25 | f2fs_attr_sec_fs_stat
      | ^
12 errors generated.

Change-Id: Ibd119d94be4e32e410564774648721577f246a4a