gpu: Prevent in_range() macro conflicts
../drivers/gpu/drm/samsung/panel/dimming.h:251:9: error: 'in_range' macro redefined [-Werror,-Wmacro-redefined]
  251 | #define in_range(i, r)                                        |         ^
../include/linux/minmax.h:298:9: note: previous definition is here
  298 | #define in_range(val, start, len)                                             |         ^

Change-Id: I43d926422eb0e5a423bacb4fc94107601a6cc37a